nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.1.cjs

# Alias 'registry' to work with tools expecting Yarn 1.x behavior
# Yarn 3.x uses npmRegistryServer instead of registry
npmRegistryServer: "https://registry.yarnpkg.com"
